// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"worker-service/app/producer"
	"worker-service/app/setup"
	"worker-service/internal-lib/utils"
)

// Injectors from wire.go:

// InitializeApp wires up all dependencies and returns the application/service instance
func InitializeApp() (*App, error) {
	defaultConfig := utils.ProvideDefaultConfig()
	config := setup.NewConfig(defaultConfig)
	logger, err := utils.InitGlobalLogger(defaultConfig)
	if err != nil {
		return nil, err
	}
	withLogger, err := utils.NewWithLogger(logger)
	if err != nil {
		return nil, err
	}
	producerProducer, err := producer.NewProducer(withLogger)
	if err != nil {
		return nil, err
	}
	app := newApp(config, withLogger, producerProducer)
	return app, nil
}
