// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"commander-service/app/mission"
	"commander-service/app/setup"
	"commander-service/app/setup/dbconfig"
	"commander-service/internal-lib/utils"
)

// Injectors from wire.go:

// InitializeApp wires up all dependencies and returns the application/service instance
func InitializeApp() (*App, error) {
	mux := setup.ProvideSingletonChiRouter()
	api := setup.ProvideSingletonHuma(mux)
	defaultConfig := utils.ProvideDefaultConfig()
	iRepository := mission.NewRepository()
	controller := mission.NewController(iRepository)
	controllers := setup.ProvideControllers(controller)
	logger, err := utils.InitGlobalLogger(defaultConfig)
	if err != nil {
		return nil, err
	}
	withLogger, err := utils.NewWithLogger(logger)
	if err != nil {
		return nil, err
	}
	commandersCampDB, err := dbconfig.ProvideCommandersCampDB(logger, withLogger, defaultConfig)
	if err != nil {
		return nil, err
	}
	app := newApp(mux, api, defaultConfig, controllers, withLogger, commandersCampDB)
	return app, nil
}
